openapi: 3.0.3
info:
  version: 1.0.0
  title: Phone contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing phone contacts
tags:
  - name: Contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
paths:
  /contacts:
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  